### PR TITLE
Clear IP on dynamic network

### PR DESCRIPTION
**Pull request by luan**
We noticed that when using the `create-swap-delete` [VM update strategy](https://bosh.io/docs/changing-deployment-vm-strategy/#usage) and dynamic networks with the Google CPI, we consistently get the following error:

```
                   L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: Google Operation 'operation-1541629462868-57a1a94827020-98416a05-e8297474' finished with an error: IP '10.0.0.2' is already being used by another resource. 
```

According to what other CPIs do, we should be ignoring that IP parameter when the network type is `dynamic`. This PR removed the IP before sending the create VM call to the IaaS to get around this issue.

We also had to remove an unused variable from `concrete_factory_test.go` because that no longer compiles on Go 1.11.

It seems that this issue is similar to #191, but we aren't sure if this fix would also fix their problem.

### CODE REVIEW

**Comment by evandbrown** [comment]
This makes sense. Thanks, @luan. I'm going to merge into `develop` and plan to cut a release tomorrow with a few more things.

**Comment by luan** [comment]
@evandbrown I didn't see a release with this yet. Any idea when you can have one out?

**Comment by evandbrown** [comment]
Hi Luan,

I've merged develop->master and that's running through Concourse. Should be
done in the next 2 hours and 29.0.0 will be live. I'll update here when
that happens.

**Comment by luan** [comment]
@evandbrown I see a v29 tag but no bosh.io release, did something go wrong on concourse when releasing this?

**Comment by evandbrown** [comment]
Fixed. I though thrabels got picked up by Bosh.io but it's GH releases.
Thanks!

**Comment by dpb587-pivotal** [comment]
No, should be tracking tarballs, and it looks like bosh.io found v29.0.0 ~12 days ago. I think it's good.

We were accidentally looking at the old cloudfoundry-incubator references that bosh.io still has with the outdated versions. Oops.

**Comment by dpb587-pivotal** [comment]
But thanks for the GitHub release notes, too!

**Comment by katter** [comment]
Create-swap-delete now works a charm. Thanks a lot for that. This is
extremely helpful and saving a huge amount of time with our growing
deployment.

Only thing I noticed was probably due to the Golang bump. Gave me some
division by zero errors when upgrading to CPI 29.0.0 with bosh 268.4.
Deleting the stuff cached under .bosh fixed this, although moving back to
the CPI referenced then causes similar issues after a successful compile of
29.0.0
Not a biggie, we’re now on 29 and will only move forward.

Cheers,

Carsten

Danny Berger <notifications@github.com> schrieb am Mi. 16. Jan. 2019 um
19:08:

**Pull request merged**
